### ISSUE TITLE
Unable to fetch bucket_name from config

### ISSUE THREAD

**Issue by xgt001** [sorentwo/carrierwave-aws#109]
Hi,
Pardon me for this being a silly question :) 
I am not sure if carrierwave-aws is able to pick up bucket name from initializer
```
undefined method `object' for nil:NilClass\nDid you mean?object_id
/usr/local/lib/ruby/gems/2.3.0/gems/carrierwave-aws-1.1.0/lib/carrierwave/storage/aws_file.rb:19:in /usr/local/lib/ruby/gems/2.3.0/gems/carrierwave-aws-1.1.0/lib/carrierwave/storage/aws_file.rb:54:in `store'
/usr/local/lib/ruby/gems/2.3.0/gems/carrierwave-aws-1.1.0/lib/carrierwave/storage/aws.rb:20:in `block in store!'
/usr/local/lib/ruby/gems/2.3.0/gems/carrierwave-aws-1.1.0/lib/carrierwave/storage/aws.rb:19:in `tap'
```

bucket object was empty for me when I tried `puts` over bucket object

Here is my carrierwave initialzer

```
require 'carrierwave-aws'
CarrierWave.configure do |config|
  config.storage    = :aws
  config.aws_bucket = 'XX-XX-XX'
  config.aws_acl    = 'private-read'

  config.aws_authenticated_url_expiration = 60 * 60 * 24 * 7

  config.aws_credentials = {
    access_key_id:     'XXXXXX',
    secret_access_key: 'XXXXXXXXX',
    region:            'ap-southeast-1'
  }

end
```

**Comment by sorentwo** [comment]
Setting the bucket is definitely support, it is necessary in fact. Is it possible that your configuration isn't getting called or the bucket is being defined dynamically?
