### ISSUE TITLE
error while saving image

### ISSUE THREAD

**Issue by aashish** [sorentwo/carrierwave-aws#129]
Hi,
Getting following error while saving the image. 

```
> model.images = [File.new(Rails.root + "sample.jpeg")]
> model.save
ArgumentError: missing required option :name
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/bucket.rb:666:in `extract_name'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/bucket.rb:21:in `initialize'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/resource.rb:69:in `new'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/gems/aws-sdk-s3-1.10.0/lib/aws-sdk-s3/resource.rb:69:in `bucket'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/gems/carrierwave-aws-1.3.0/lib/carrierwave/storage/aws_file.rb:106:in `bucket'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/gems/carrierwave-aws-1.3.0/lib/carrierwave/storage/aws_file.rb:19:in `file'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/gems/carrierwave-aws-1.3.0/lib/carrierwave/storage/aws_file.rb:59:in `store'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/gems/carrierwave-aws-1.3.0/lib/carrierwave/storage/aws.rb:18:in `block in store!'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/gems/carrierwave-aws-1.3.0/lib/carrierwave/storage/aws.rb:17:in `tap'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/gems/carrierwave-aws-1.3.0/lib/carrierwave/storage/aws.rb:17:in `store!'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/bundler/gems/carrierwave-c0b7fab3a14d/lib/carrierwave/uploader/store.rb:66:in `block in store!'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/bundler/gems/carrierwave-c0b7fab3a14d/lib/carrierwave/uploader/callbacks.rb:15:in `with_callbacks'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/bundler/gems/carrierwave-c0b7fab3a14d/lib/carrierwave/uploader/store.rb:65:in `store!'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/bundler/gems/carrierwave-c0b7fab3a14d/lib/carrierwave/mounter.rb:100:in `each'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/bundler/gems/carrierwave-c0b7fab3a14d/lib/carrierwave/mounter.rb:100:in `store!'
	from /home/xxxxxxx/.rvm/gems/ruby-2.4.1@xxxxxxx/bundler/gems/carrierwave-c0b7fab3a14d/lib/carrierwave/mount.rb:395:in `store_images!'
```
Thank You,
Aashish Kiran

**Comment by sorentwo** [comment]
I’m not sure how tour uploader is configured, but I’m not familiar with any way to assign an array of files to a mounted uploader.

This is not a carrierwave-was issue.

**Comment by muhammadyana** [comment]
Hello, i'm getting some error. 
`user.remote_avatar_url = "https://s3-ap-southeast-1.amazonaws.com/muhammadyana/images/avatar/yana-thumbnail-forest-3-4-small.jpg"`
`user.save!`
`ArgumentError: missing required option :name`
`from /Users/yana/.rvm/gems/ruby-2.6.2/gems/aws-sdk-s3-1.47.0/lib/aws-sdk-s3/bucket.rb:691:in `extract_name'`

and my gemfile
`gem 'carrierwave', "~> 1.3.1"`
`gem 'carrierwave-aws', "~> 1.3"`

Thanks

**Comment by MarceloCajueiro** [comment]
https://stackoverflow.com/questions/50912795/missing-required-option-name
