### ISSUE TITLE
AWS sdk v3?

### ISSUE THREAD

**Issue by brandoncc** [sorentwo/carrierwave-aws#138]
Is this gem compatible with aws sdk v3? We are experiencing an issue when we try to upgrade Rails and I was told on the aws-sdk-ruby repo that it is related to a multithreading issue with sdk v2.

Here is our stack trace:

```
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'carrierwave-aws'. (Bundler::GemRequireError)
remote:        Gem Load Error is: uninitialized constant Seahorse::Client::NetHttp::Handler::SocketError
remote:        Backtrace for gem load error is:
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/seahorse/client/net_http/handler.rb:21:in `<class:Handler>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/seahorse/client/net_http/handler.rb:9:in `<module:NetHttp>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/seahorse/client/net_http/handler.rb:5:in `<module:Client>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/seahorse/client/net_http/handler.rb:4:in `<module:Seahorse>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/seahorse/client/net_http/handler.rb:3:in `<top (required)>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:21:in `require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:21:in `block in load'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:18:in `each'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:18:in `load'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:23:in `block in load'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:18:in `each'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:18:in `load'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:23:in `block in load'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:18:in `each'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core/eager_loader.rb:18:in `load'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/aws-sdk-core-2.11.188/lib/aws-sdk-core.rb:521:in `eager_autoload!'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/carrierwave-aws-1.2.0/lib/carrierwave/storage/aws.rb:5:in `<top (required)>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/carrierwave-aws-1.2.0/lib/carrierwave-aws.rb:5:in `require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/carrierwave-aws-1.2.0/lib/carrierwave-aws.rb:5:in `<top (required)>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:82:in `require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:77:in `each'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:77:in `block in require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:66:in `each'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler/runtime.rb:66:in `require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/bundler-1.15.2/lib/bundler.rb:108:in `require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/config/application.rb:5:in `<top (required)>'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/command/actions.rb:15:in `require'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/commands/runner/runner_command.rb:27:in `perform'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/command/base.rb:63:in `perform'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/command.rb:44:in `invoke'
remote:        /tmp/build_791b64b4e0c9cbc2ec8d163d638b5660/vendor/bundle/ruby/2.5.0/gems/railties-5.1.6.1/lib/rails/commands.rb:16:in `<top (required)>'
remote:        bin/rails:9:in `require'
remote:        bin/rails:9:in `<main>'
```

They said:

> For background, the issue you're seeing tends to happen in multi-threaded environments due to autoloading, and was an issue fixed in major version 3 of the SDK. If you're required to use major version 2, you may want to require the aws-sdk or aws-sdk-core gem up front and call Aws.eager_autoload! to get around this.

---

We would prefer upgrading to v3 if possible.

**Comment by sorentwo** [comment]
Honestly I haven't tried. If you would like to try and submit a PR it would be welcome.

**Comment by brandoncc** [comment]
Sounds good. I will open a PR if the specs pass. Thanks @sorentwo

**Comment by brandoncc** [comment]
No update needed, it pulls in sdk v3 as is and specs pass. Closing, thanks for the feedback.
