### ISSUE TITLE
Error in README: deprecated config.asset_host_public = true

### ISSUE THREAD

**Issue by charneykaye** [sorentwo/carrierwave-aws#141]
As of `carrierwave` 1.3.1 there is no **asset_host_public** configuration parameter

See [carrierwave/uploader/configuration.rb](https://github.com/carrierwaveuploader/carrierwave/blob/v1.3.1/lib/carrierwave/uploader/configuration.rb)

The nonexistent parameter is specified in the current README:

    config.asset_host_public = true

So when I followed the instructions I get an error:

```
==> log/myapp_web.err.log <==
/myapp/config/environments/development.rb:58:in `block (2 levels) in <top (required)>': undefined method `asset_host_public=' for CarrierWave::Uploader::Base:Class (NoMethodError)
Did you mean?  asset_host=
        from /usr/local/bundle/gems/carrierwave-1.3.1/lib/carrierwave/uploader/configuration.rb:161:in `configure'
        from /usr/local/bundle/gems/carrierwave-1.3.1/lib/carrierwave.rb:14:in `configure'
        from /myapp/config/environments/development.rb:50:in `block in <top (required)>'
```

**Comment by charneykaye** [comment]
Hey, I'm implementing carrierwave-aws for the first time now, so will confirm if the README is the only item affected by this issue.
