### ISSUE TITLE
AWS::S3::Errors::NoSuchKey: No Such Key error on store

### ISSUE THREAD

**Issue by donaldpiret** [sorentwo/carrierwave-aws#21]
I'm attempting to use carrierwave_backgrounder with carrierwave-aws and am running into the following error: AWS::S3::Errors::NoSuchKey: No Such Key error on store

Here is a full stack trace:

```
AWS::S3::Errors::NoSuchKey: No Such Key
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-1.49.0/lib/aws/core/client.rb:375:in `return_or_raise'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-1.49.0/lib/aws/core/client.rb:476:in `client_request'
    (eval):3:in `head_object'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-1.49.0/lib/aws/s3/s3_object.rb:293:in `head'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/aws-sdk-1.49.0/lib/aws/s3/s3_object.rb:325:in `content_type'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/carrierwave-aws-0.4.1/lib/carrierwave/storage/aws.rb:46:in `content_type'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/carrierwave-aws-0.4.1/lib/carrierwave/storage/aws.rb:113:in `uploader_write_options'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/carrierwave-aws-0.4.1/lib/carrierwave/storage/aws.rb:77:in `store'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/carrierwave-aws-0.4.1/lib/carrierwave/storage/aws.rb:16:in `block in store!'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/carrierwave-aws-0.4.1/lib/carrierwave/storage/aws.rb:15:in `tap'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/carrierwave-aws-0.4.1/lib/carrierwave/storage/aws.rb:15:in `store!'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:59:in `block in store!'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:58:in `store!'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:375:in `store!'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:207:in `store_file!'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/carrierwave_backgrounder-0.4.1/lib/backgrounder/orm/base.rb:89:in `store_file!'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:424:in `block in make_lambda'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:221:in `call'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:221:in `block in halting_and_conditional'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:215:in `call'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:86:in `call'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:86:in `run_callbacks'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/callbacks.rb:302:in `create_or_update'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/persistence.rb:125:in `save!'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/validations.rb:57:in `save!'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/transactions.rb:273:in `block in save!'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/transactions.rb:208:in `transaction'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
    /Users/donald/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.1.5/lib/active_record/transactions.rb:273:in `save!'
```

FYI the value of new_file inside the content_type method inside storage/aws.rb:46 is as follows:

```
#<CarrierWave::Storage::AWS::File:0x007fc88e4a14c0 @uploader=#<DeviceIdentifierListUploader:0x007fc8969c9f08 @model=#<DeviceIdentifierList id: 18, name: "aertaeryaeryaertae", user_id: -1, latest_sha1: nil, created_at: "2014-08-21 13:39:41", updated_at: "2014-08-21 13:39:41", customer_id: 2, file: "ifa_list_example_file.csv", file_processing: false, file_tmp: nil, state: "processing">, @mounted_as=:file, @cache_id="1408628381-32549-8749", @filename="ifa_list_example_file.csv", @original_filename="ifa_list_example_file.csv", @file=#<CarrierWave::Storage::AWS::File:0x007fc88e4a14c0 ...>, @versions={}, @upload_directory="/Users/donald/Projects/poblano/public/uploads/tmp/1408628381-32549-8749", @storage=#<CarrierWave::Storage::AWS:0x007fc894e5a0d8 @uploader=#<DeviceIdentifierListUploader:0x007fc8969c9f08 ...>, @connection=<AWS::S3>>>, @connection=<AWS::S3>, @path="uploads/device_identifier_list/file/18/ifa_list_example_file.csv">
```

Any help would be greatly appreciated

**Comment by mcasimir** [comment]
Hi, this issue is still present. I think this may happen in distributed environments, not sure why but it seems sometimes S3 upload fails but data are still stored to db.

The right way, although this may be caused by misbehaviours with S3 protocol,  should be to handle this exception in carrierwave, treating it like other not found images, so trying to respond with the default image (if one) and avoiding raising exception in any case.

**Comment by sorentwo** [comment]
@mcasimir: Are you suggesting just swallowing the error and faking a `nil` response? I'm not sure I'm comfortable with that. How prevalent is this problem? I've been running this in production with various configurations and in a multi-threaded environment for years without running into this error.
