### ISSUE TITLE
Aws::S3::Errors::InvalidArgument Error on Remote URL Upload

### ISSUE THREAD

**Issue by krnjn** [sorentwo/carrierwave-aws#56]
Here's the stack trace which should help point to the file/command causing the issue:

```
Aws::S3::Errors::InvalidArgument: 
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/aws-sdk-core-2.0.48/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/aws-sdk-core-2.0.48/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/aws-sdk-core-2.0.48/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/aws-sdk-core-2.0.48/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/aws-sdk-core-2.0.48/lib/seahorse/client/plugins/response_target.rb:18:in `call'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/aws-sdk-core-2.0.48/lib/seahorse/client/request.rb:70:in `send_request'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/aws-sdk-core-2.0.48/lib/seahorse/client/base.rb:216:in `block (2 levels) in define_operation_methods'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/aws-sdk-resources-2.0.48/lib/aws-sdk-resources/request.rb:24:in `call'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/aws-sdk-resources-2.0.48/lib/aws-sdk-resources/operations.rb:41:in `call'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/aws-sdk-resources-2.0.48/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/carrierwave-aws-0.6.0/lib/carrierwave/storage/aws_file.rb:56:in `store'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/carrierwave-aws-0.6.0/lib/carrierwave/storage/aws.rb:16:in `block in store!'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/carrierwave-aws-0.6.0/lib/carrierwave/storage/aws.rb:15:in `tap'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/carrierwave-aws-0.6.0/lib/carrierwave/storage/aws.rb:15:in `store!'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:59:in `block in store!'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/carrierwave-0.10.0/lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
... 16 levels...
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/activerecord-4.2.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/activerecord-4.2.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/activerecord-4.2.3/lib/active_record/transactions.rb:291:in `save!'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/activerecord-4.2.3/lib/active_record/persistence.rb:51:in `create!'
	from (irb):3
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/karanjain/.rvm/gems/ruby-2.2.0@tinygive/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

And here's the gem versions being used:

```
carrierwave-aws (0.6.0)
      aws-sdk (~> 2.0.47)
      carrierwave (~> 0.7)
 aws-sdk (2.0.48)
      aws-sdk-resources (= 2.0.48)
    aws-sdk-core (2.0.48)
      builder (~> 3.0)
      jmespath (~> 1.0)
      multi_json (~> 1.0)
    aws-sdk-resources (2.0.48)
      aws-sdk-core (= 2.0.48)
```

**Comment by sorentwo** [comment]
@krnjn: Please take a look at https://github.com/sorentwo/carrierwave-aws/issues/57#issuecomment-117279126, I think you are running into the same issue.

**Comment by krnjn** [comment]
@sorentwo here's my config block – I don't think its the same issue:

```
CarrierWave.configure do |config|
  ## FOR HEROKU
  config.root = Rails.root.join('tmp') # adding these...
  config.cache_dir = 'carrierwave' # ...two lines

  ## AWS CONFIG
  config.storage    =  :aws                  # required
  config.aws_bucket =  ENV['S3_BUCKET']      # required
  config.aws_acl    =  :public_read
  config.aws_credentials = {
    access_key_id:      ENV['S3_KEY'],       # required
    secret_access_key:  ENV['S3_SECRET'],     # required
    region:             ENV['S3_REGION']      # required  
  }
end
```

**Comment by sorentwo** [comment]
@krnjn: Are you getting this consistently, only from uploaded files? Can you give me some more context to recreate the bug?

**Comment by krnjn** [comment]
@sorentwo: if you use the dependencies I listed above (mainly just use carrierwave-aws 0.6.0) and attempt to save an image/attachment/file to AWS using carrierwave's remote_url method from the rails console, you'll get the error. For example, create a User model with attributes `:name` and `:avatar` mounted via Carrierwave with `mount_uploader :avatar, ImageUploader`, and then try:

```
User.create!(name: 'test name', remote_avatar_url: 'http://www.femto.it/wp-content/uploads/2014/04/default-user-avatar.png')
```

It will not accept the `remote_avatar_url` in this format and save it to S3. There may be additional cases in which it does not work, but this was my primary issue.

**Comment by sorentwo** [comment]
That's very helpful, thank you.

**Comment by philipgiuliani** [comment]
Im getting Aws::S3::Errors::InvalidArgument without more information after updating from 0.5.0 to 0.6.0. But im not using remote_url's.

@krnjn 
According the Changelog you have to change `:public_read` to `"public-read"`

**Comment by sorentwo** [comment]
@philipgiuliani: You are absolutely correct, the `:public_read` vs `'public-read'` difference is probably the issue here.

**Comment by philipgiuliani** [comment]
Oh i havent even tested if this is causing the issue for me, i also had forgotten it when i updated!

I will try to update it again tomorrow :)

**Comment by krnjn** [comment]
@sorentwo that seemed to fix it. Thanks @philipgiuliani!

**Comment by sorentwo** [comment]
I'm adding config validation to the `1.X` branch to catch these sorts of problems during startup, rather than at runtime.

**Comment by mdchaney** [comment]
This is still a problem at the end of 2019.

**Comment by sorentwo** [comment]
@mdchaney A pull request is always welcome. This issue is over four years old and quite honestly, I don't remember it at all.

**Comment by mdchaney** [comment]
If I get time next month I'll track it down.  My belief is that it's an issue when the acl on the file is set to "public" but the bucket is set to private.
